"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
# settings.py
from django.utils.translation import gettext_lazy as _
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6+8)3h-i7mjp4*k)_md2pp!9h$@12!g(7rwj6swd2*l-_@e1&1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'produition.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'produition',
    'crispy_forms',
    'crispy_bootstrap5', 
    'allauth.socialaccount.providers.google',
    'rosetta',  
    'autotranslate' 
]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    #  'django.contrib.auth.backends.ModelBackend',
    # 'allauth.account.auth_backends.AuthenticationBackend',
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend', # <--- DOIT ÊTRE ICI
]
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

WSGI_APPLICATION = 'backend.wsgi.application'

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True
# USE_L10N = True
LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
]
# LANGUAGES = [
#     ('fr', _('Français')),
#     ('en', _('English')),
#     ('es', _('Español')),
#     ('de', _('Deutsch')),
#     ('pt', _('Português')),
# ]



TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# L'URL vers laquelle Django redirige les utilisateurs non connectés
# LOGIN_URL = 'connexion'  # Utilisez ici le 'name' que vous avez donné dans votre urls.py

# L'URL vers laquelle l'utilisateur est envoyé APRÈS s'être connecté avec succès
# LOGIN_REDIRECT_URL = '/'  # Ou le nom de votre page d'accueil (ex: 'tableau_de_bord')


LOGIN_REDIRECT_URL = '/tableau_de_bord/'
LOGOUT_REDIRECT_URL = 'connexion'
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # ou 'username'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'optional'  
# 'mandatory' pour forcer la vérification email
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
LOGIN_URL = 'connexion'

SITE_ID = 1

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# =============================================
# EMAIL CONFIGURATION
# =============================================
# Configuration pour l'envoi d'emails de contact avec confirmation

# Backend d'envoi d'email (console pour développement)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Pour le développement
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Pour la production

# Configuration SMTP pour Gmail (exemple)
# Décommentez et configurez pour la production:
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'votre-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'votre-mot-de-passe-app'

# Configuration alternative avec un service SMTP personnalisé:
# EMAIL_HOST = 'smtp.votreserveur.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'votre-email@votredomaine.com'
# EMAIL_HOST_PASSWORD = 'votre-mot-de-passe'

# Email par défaut pour l'envoi
DEFAULT_FROM_EMAIL = 'noreply@kinera-filmfixers.com'

# List of admins who receive admin notifications
ADMINS = [
    ('Admin', 'admin@kinera-filmfixers.com'),
]

# Email pour les notifications admin (optionnel)
ADMIN_EMAIL = 'admin@kinera-filmfixers.com'

# Timeout pour l'envoi d'emails (en secondes)
EMAIL_TIMEOUT = 10

# Logging des emails
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/email.log'),
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'produition.views.views_contact': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Créer le répertoire logs s'il n'existe pas
import os as os_module
os_module.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

