FROM python:3.10-slim

WORKDIR /app

# Installer les dépendances système souvent nécessaires
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Copier requirements.txt et installer Python packages
COPY API/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le backend complet
COPY API/backend/ .

CMD ["python", "-m", "gunicorn", "project.wsgi:application", "--bind", "0.0.0.0:8000"]
