FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

COPY API/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY API/backend/ .

CMD ["python", "-m", "gunicorn", "project.wsgi:application", "--bind", "0.0.0.0:8000"]
