# 1. Image légère
FROM python:3.10-slim

# 2. Variables d'environnement
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 3. Dépendances système pour MySQL / PostgreSQL / Pillow
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    libpq-dev \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# 4. Répertoire de travail
WORKDIR /app

# 5. Copier requirements.txt depuis le chemin réel
COPY API/backend/requirements.txt .

# 6. Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# 7. Copier le backend complet
COPY API/backend/ .

# 8. CMD pour lancer Django avec gunicorn
CMD ["python", "-m", "gunicorn", "project.wsgi:application", "--bind", "0.0.0.0:8000"]
