# Generated by Django 5.2.11 on 2026-02-22 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100, verbose_name="Nom de l'expéditeur")),
                ('sender_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name="Email de l'expéditeur")),
                ('sender_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('category', models.CharField(choices=[('general', 'Général'), ('devis', 'Devis'), ('reclamation', 'Réclamation'), ('partenariat', 'Partenariat')], default='general', max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('repondu', 'Répondu'), ('archive', 'Archivé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de l'email")),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='produition__created_9fcdd7_idx'), models.Index(fields=['status'], name='produition__status_18cdea_idx'), models.Index(fields=['sender_email'], name='produition__sender__17b344_idx')],
            },
        ),
    ]
