# Generated by Django 5.2.11 on 2026-02-24 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produition', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la vidéo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('hero', 'Héro'), ('portfolio', 'Portfolio'), ('about', 'À propos'), ('service', 'Services'), ('testimonial', 'Témoignage'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('video_file', models.FileField(help_text='Formats acceptés: MP4, WebM, OGG', upload_to='videos/%Y/%m/', verbose_name='Fichier vidéo')),
                ('duration', models.IntegerField(blank=True, help_text='Durée de la vidéo en secondes', null=True, verbose_name='Durée (secondes)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Image de preview pour la vidéo', null=True, upload_to='thumbnails/%Y/%m/', verbose_name='Miniature')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('custom_url', models.CharField(blank=True, help_text='Laisser vide pour générer automatiquement', max_length=200, unique=True, verbose_name='URL personnalisée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-order', '-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='produition__created_5ad106_idx'), models.Index(fields=['category'], name='produition__categor_78e25d_idx'), models.Index(fields=['status'], name='produition__status_6acc50_idx'), models.Index(fields=['is_featured'], name='produition__is_feat_0f8751_idx')],
            },
        ),
    ]
