# Generated by Django 5.2.11 on 2026-02-24 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produition', '0003_video'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='video',
            name='produition__created_5ad106_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='produition__categor_78e25d_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='produition__status_6acc50_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='produition__is_feat_0f8751_idx',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='custom_url',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='URL personnalisée'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée (secondes)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/', verbose_name='Miniature'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/%Y/%m/', verbose_name='Fichier vidéo'),
        ),
    ]
