# Generated by Django 5.2.11 on 2026-02-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produition', '0004_remove_video_produition__created_5ad106_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Nouvelle vidéo', max_length=200, verbose_name='Titre de la vidéo'),
        ),
    ]
