# Generated by Django 5.2.11 on 2026-02-26 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produition', '0005_video_description_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('project_type', models.CharField(choices=[('photo', 'Photographie'), ('video', 'Vidéo'), ('mixed', 'Photo & Vidéo')], default='photo', max_length=20, verbose_name='Type de réalisation')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet Portfolio',
                'verbose_name_plural': 'Portfolio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10)),
                ('file', models.FileField(upload_to='portfolio/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/%Y/%m/')),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='produition.portfolioproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
