# Generated by Django 5.2.11 on 2026-02-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produition', '0006_portfolioproject_portfoliomedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomedia',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='produition.portfolioproject'),
        ),
    ]
